
import java.awt.Dimension;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JEditorPane;
import javax.swing.JInternalFrame;
import javax.swing.JScrollPane;
import org.json.JSONObject;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author aayushshivam7
 */
public class CodeforcesBlog extends javax.swing.JInternalFrame {

    JEditorPane jpane;

    /**
     * Creates new form CodeforcesBlogd
     */
    NewApplication jfrm;

    public CodeforcesBlog(NewApplication jfrm) {
        this.jfrm = jfrm;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setClosable(true);

        jButton1.setText("dp");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("graph");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("tree");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("math");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JInternalFrame dp = new JInternalFrame();
        jpane = new JEditorPane();
        jpane.setContentType("text/html");
        JScrollPane jpp = new JScrollPane(jpane);
      //  jpane.add(jpp);
        jpane.setEditable(false);
        dp.add(jpp);
        jpane.setText(title);
        this.jfrm.jDesktopPane1.add(dp);
        dp.setVisible(true);
        dp.setBounds(40, 40,800,800);
         Dimension desktopSize = this.jfrm.getSize();
        Dimension jInternalFrameSize = dp.getSize();
        dp.setMaximizable(true);

        dp.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
        this.jfrm.jDesktopPane1.moveToFront(dp);
        dp.show();
        dp.setClosable(true);
        try {
            handler("43256");
        } catch (IOException ex) {
            Logger.getLogger(CodeforcesBlog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JInternalFrame dp = new JInternalFrame();
        jpane = new JEditorPane();
        jpane.setContentType("text/html");
        JScrollPane jpp = new JScrollPane(jpane);
      //  jpane.add(jpp);
        jpane.setEditable(false);
        dp.add(jpp);
        jpane.setText(title);
        this.jfrm.jDesktopPane1.add(dp);
        dp.setVisible(true);
        dp.setBounds(40, 40,800,800);
         Dimension desktopSize = this.jfrm.getSize();
        Dimension jInternalFrameSize = dp.getSize();
        dp.setMaximizable(true);

        dp.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
        this.jfrm.jDesktopPane1.moveToFront(dp);
        dp.show();
        dp.setClosable(true);
        try {
            handler("3075");
        } catch (IOException ex) {
            Logger.getLogger(CodeforcesBlog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JInternalFrame dp = new JInternalFrame();
        jpane = new JEditorPane();
        jpane.setContentType("text/html");
        JScrollPane jpp = new JScrollPane(jpane);
      //  jpane.add(jpp);
        jpane.setEditable(false);
        dp.add(jpp);
        jpane.setText(title);
        this.jfrm.jDesktopPane1.add(dp);
        dp.setVisible(true);
        dp.setBounds(40, 40,800,800);
         Dimension desktopSize = this.jfrm.getSize();
        Dimension jInternalFrameSize = dp.getSize();
        dp.setMaximizable(true);

        dp.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
        this.jfrm.jDesktopPane1.moveToFront(dp);
        dp.show();
        dp.setClosable(true);
        try {
            handler("15890");
        } catch (IOException ex) {
            Logger.getLogger(CodeforcesBlog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JInternalFrame dp = new JInternalFrame();
        jpane = new JEditorPane();
        jpane.setContentType("text/html");
        JScrollPane jpp = new JScrollPane(jpane);
      //  jpane.add(jpp);
        jpane.setEditable(false);
        dp.add(jpp);
        jpane.setText(title);
        this.jfrm.jDesktopPane1.add(dp);
        dp.setVisible(true);
        dp.setBounds(40, 40,800,800);
         Dimension desktopSize = this.jfrm.getSize();
        Dimension jInternalFrameSize = dp.getSize();
        dp.setMaximizable(true);

        dp.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
        this.jfrm.jDesktopPane1.moveToFront(dp);
        dp.show();
        dp.setClosable(true);
        try {
            handler("46620");
        } catch (IOException ex) {
            Logger.getLogger(CodeforcesBlog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    public void handler(String algo) throws MalformedURLException, IOException {
        String s = "http://codeforces.com/api/blogEntry.view?blogEntryId="+algo;
        URL url = new URL(s);
        Scanner scan = new Scanner(url.openStream());
        String str = new String();
        while (scan.hasNext()) {
            str += scan.nextLine();
        }
        scan.close();
        JSONObject obj = new JSONObject(str);
        if (!obj.getString("status").equals("OK")) {
            //jsonText.setText("User is not on CodeForces!!!!!");  
            return;
        }
        //  return;
        // get the first result
        JSONObject res = obj.getJSONObject("result");
        System.out.println("he");
        System.out.println(res + "");
        String content = res.getString("content");
        jpane.setText(content);
        System.out.println(content);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
