
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JViewport;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;
import javax.swing.text.Highlighter.HighlightPainter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class FindAndReplaceFrame1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form FindAndReplaceFrame1
     */
   ClassForCodeAreaTab findReplace ;
   // int lastPosReplace=0;
    String codeAreaString;
    String temporaryString;
    String prev="";
    int lastPosFind;
    FindAndReplaceFrame1(ClassForCodeAreaTab cc) {
        this.findReplace = cc ;
        initComponents();
    }
    public void initialize(String textCheck)
    {
        codeAreaString=textCheck;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        replaceWalaFind2 = new javax.swing.JTextField();
        findButton1 = new javax.swing.JButton();
        cancelIt1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        replaceWalaFind3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        replaceHere1 = new javax.swing.JTextField();
        replaceButton1 = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cancelIt = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        replaceWalaFind1 = new javax.swing.JTextField();
        findButton = new javax.swing.JButton();

        jLabel5.setText("Text To Find :");

        replaceWalaFind2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceWalaFind2ActionPerformed(evt);
            }
        });

        findButton1.setText("Find");
        findButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findButton1ActionPerformed(evt);
            }
        });

        cancelIt1.setText("Cancel");
        cancelIt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelIt1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(findButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelIt1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(replaceWalaFind2))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(replaceWalaFind2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelIt1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        setClosable(true);

        jLabel6.setText("Text To Find :");

        replaceWalaFind3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceWalaFind3ActionPerformed(evt);
            }
        });

        jLabel7.setText("Replace With:");

        replaceHere1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceHere1ActionPerformed(evt);
            }
        });

        replaceButton1.setText("Replace");
        replaceButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceButton1ActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(replaceButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(replaceWalaFind3)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(replaceHere1))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(replaceWalaFind3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(replaceHere1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(replaceButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        jTabbedPane1.addTab("Replace", jPanel2);

        cancelIt.setText("Cancel");
        cancelIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelItActionPerformed(evt);
            }
        });

        jLabel4.setText("Text To Find :");

        replaceWalaFind1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceWalaFind1ActionPerformed(evt);
            }
        });

        findButton.setText("Find");
        findButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(findButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addComponent(cancelIt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(replaceWalaFind1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(replaceWalaFind1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelIt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Find", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelIt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelIt1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelIt1ActionPerformed

    private void findButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findButton1ActionPerformed
      /*  String find=replaceWalaFind1.getText();

        if (find.equals(null)) {
            JOptionPane.showMessageDialog(null,"Value entered can't be null", "InfoBox: " , JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JScrollPane scroll = (JScrollPane) findReplace.jframe.jTabbedPane.getSelectedComponent();
            JViewport viewport = scroll.getViewport();                        // first extract viewport from scrollpane then extract JTextArea from Viewport
            JTextArea area = (JTextArea) viewport.getView();
            Highlighter highlighter=area.getHighlighter();
            HighlightPainter painter=new DefaultHighlighter.DefaultHighlightPainter(Color.BLUE);
            int p0=area.getText().indexOf(find);
            int p1=p0+find.length();
            try {
                highlighter.addHighlight(p0,p1,painter);
            } catch (BadLocationException ex) {
                Logger.getLogger(FindAndReplaceFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

        }*/
    }//GEN-LAST:event_findButton1ActionPerformed

    private void replaceWalaFind2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceWalaFind2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_replaceWalaFind2ActionPerformed

    private void findButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findButtonActionPerformed
        String find=replaceWalaFind1.getText();

        if (find.equals("")) {
            JOptionPane.showMessageDialog(null,"Value entered can't be null", "InfoBox: " , JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JScrollPane scroll = (JScrollPane) findReplace.jframe.jTabbedPane.getSelectedComponent();
            JViewport viewport = scroll.getViewport();                        // first extract viewport from scrollpane then extract JTextArea from Viewport
            JTextArea area = (JTextArea) viewport.getView();
            Highlighter highlighter=area.getHighlighter();
            HighlightPainter painter=new DefaultHighlighter.DefaultHighlightPainter(Color.YELLOW);
            String input=area.getText();
            highlighter.removeAllHighlights();//(lastPosFind,lastPosFind+prev.length(),new DefaultHighlighter.DefaultHighlightPainter(Color.WHITE));
            if(!find.equals(prev))
            {
            lastPosFind=0;
            }
            if(lastPosFind!=input.length()){
           // System.out.println("find"+" "+find+" "+"prev"+" "+prev+" "+"last"+" "+lastPosFind+"\n");
            int p0=(input.substring(lastPosFind,input.length())).indexOf(find);
            if(p0!=-1)
            {
                
            p0=p0+lastPosFind;
            int p1=p0+find.length();
            try {
                highlighter.addHighlight(p0,p1,painter);
            } catch (BadLocationException ex) {
                Logger.getLogger(FindAndReplaceFrame1.class.getName()).log(Level.SEVERE, null, ex);
            }
          lastPosFind=p1;
          prev=find;
         // System.out.println("last"+" "+lastPosFind+" "+"prev"+" "+prev+"\n");
        }
        }
        }
    }//GEN-LAST:event_findButtonActionPerformed

    private void replaceWalaFind1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceWalaFind1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_replaceWalaFind1ActionPerformed

    private void cancelItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelItActionPerformed
        JScrollPane scroll = (JScrollPane) findReplace.jframe.jTabbedPane.getSelectedComponent();
            JViewport viewport = scroll.getViewport();                        // first extract viewport from scrollpane then extract JTextArea from Viewport
            JTextArea area = (JTextArea) viewport.getView();
            Highlighter highlighter=area.getHighlighter();
            HighlightPainter painter=new DefaultHighlighter.DefaultHighlightPainter(Color.YELLOW);
            String input=area.getText();
            highlighter.removeAllHighlights();
        this.dispose();
    }//GEN-LAST:event_cancelItActionPerformed

    private void replaceWalaFind3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceWalaFind3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_replaceWalaFind3ActionPerformed

    private void replaceHere1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceHere1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_replaceHere1ActionPerformed

    private void replaceButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceButton1ActionPerformed
        String replaceFind = replaceWalaFind3.getText(),replaceWith=null;
        if (replaceFind.equals("")) {
            JOptionPane.showMessageDialog(null,"Value entered can't be null", "InfoBox: " , JOptionPane.INFORMATION_MESSAGE);
        } else {
            replaceWith = replaceHere1.getText();
            JScrollPane scroll = (JScrollPane) findReplace.jframe.jTabbedPane.getSelectedComponent();
            JViewport viewport = scroll.getViewport();                        // first extract viewport from scrollpane then extract JTextArea from Viewport
            JTextArea area = (JTextArea) viewport.getView();
            String input="";
            input=area.getText();
            String input2=input.substring(0,input.length());
            int pos=input2.indexOf(replaceFind);
            
            // input = findReplace.jframe.jTabbedPane.setSelectedIndex(findReplace.jframe.jTabbedPane.getSelectedIndex()).getText();
            if (pos != -1) {

                String s1 = input.substring(0,pos);
                int len = replaceFind.length();                  //farzi string ki length
                String s2 = input.substring(pos + len, input.length());   // farzi string
                String s3 = s1 + replaceWith + s2;                                                  // farzi string
                temporaryString=s3;
                findReplace.codeArea.setText(temporaryString);
                
            }

        }
        
    }//GEN-LAST:event_replaceButton1ActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
       JScrollPane scroll = (JScrollPane) findReplace.jframe.jTabbedPane.getSelectedComponent();
            JViewport viewport = scroll.getViewport();                        // first extract viewport from scrollpane then extract JTextArea from Viewport
            JTextArea area = (JTextArea) viewport.getView();
            Highlighter highlighter=area.getHighlighter();
            HighlightPainter painter=new DefaultHighlighter.DefaultHighlightPainter(Color.YELLOW);
            String input=area.getText();
            highlighter.removeAllHighlights();
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton cancelIt;
    private javax.swing.JButton cancelIt1;
    private javax.swing.JButton findButton;
    private javax.swing.JButton findButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton replaceButton1;
    private javax.swing.JTextField replaceHere1;
    private javax.swing.JTextField replaceWalaFind1;
    private javax.swing.JTextField replaceWalaFind2;
    private javax.swing.JTextField replaceWalaFind3;
    // End of variables declaration//GEN-END:variables
}
