
import java.awt.Event;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.net.URLEncoder;
import java.util.Scanner;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import org.json.JSONArray;
import org.json.JSONObject;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aayushshivam7
 */
public class JsonContent extends javax.swing.JInternalFrame {

    /**
     * Creates new form JsonContent
     */
    public JsonContent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        banda = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jsonText = new javax.swing.JEditorPane();

        setClosable(true);

        jsonText.setEditable(false);
        jsonText.setContentType("text/html"); // NOI18N
        jScrollPane2.setViewportView(jsonText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(banda, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(banda, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 155, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void showmatter(String user) throws IOException, URISyntaxException{
        String s = "http://codeforces.com/api/user.info?handles="+user;
    URL url = new URL(s);
    Scanner scan = new Scanner(url.openStream());
    String str = new String();
    while (scan.hasNext())
        str += scan.nextLine();
    scan.close();
    JSONObject obj = new JSONObject(str);
    if ( !obj.getString("status").equals("OK")){
         jsonText.setText("User is not on CodeForces!!!!!");  
         return ;
    }
      //  return;
    // get the first result
    JSONObject res = obj.getJSONArray("result").getJSONObject(0);
    String rating = res.get("rating").toString();
    String contribution = res.get("contribution").toString();
    String lastOnline = res.get("lastOnlineTimeSeconds").toString();
    String friendCount = res.get("friendOfCount").toString();
    String titlephoto = res.get("titlePhoto").toString();
    String rank = res.get("rank").toString();
    String handle = res.get("handle").toString();
    String maxRank = res.get("maxRank").toString();
    String avatar = res.get("avatar").toString();
    jsonText.setText("<big><b>Handle :  </b><font color='red'><b>"+
            handle+"</b></big></font><hr><br>Rating: <b>"+rating+
            "</b><br><hr>Contribution: <b>"+contribution +
            "</b><br><hr>friendCount: <b>"+friendCount+"</b><br><hr>"+
             "rank: <b>"+rank+"</b><br><hr>Max Rank: <b>"+ 
            maxRank+"</b><br>");
    BufferedImage image = null;
    
    //banda.add(new JLabel("",new ImageIcon(image),JLabel.CENTER)) ;
    try{
        image = ImageIO.read(new URL(avatar));
        
    }catch(IOException e){
        e.printStackTrace();
    }
    Image dimg = image.getScaledInstance(banda.getWidth(),
            banda.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon imgcon = new ImageIcon(dimg);
    banda.setIcon(imgcon);
   // System.out.println(str);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel banda;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JEditorPane jsonText;
    // End of variables declaration//GEN-END:variables
}
