
import java.awt.Font;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class TextStylesInternalFrame extends javax.swing.JInternalFrame {
    ClassForCodeAreaTab chngFont;
    int recentType;
    /**
     * Creates new form TextStylesInternalFrame
     */
    public TextStylesInternalFrame(ClassForCodeAreaTab cc) {
        chngFont = cc;
        recentType = 1;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fontType = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fontStyle = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        fontSize = new javax.swing.JSpinner();
        okChangeFont = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setClosable(true);
        setTitle("Change Font Style");
        setInheritsPopupMenu(true);
        setNormalBounds(new java.awt.Rectangle(0, 0, 100, 100));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        fontType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monospaced", "Serif", "SansSerif", "Default", "Dialog" }));
        fontType.setBorder(null);
        fontType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fontTypeActionPerformed(evt);
            }
        });

        jLabel1.setText("Font Type");

        jLabel2.setText("Font Style");

        fontStyle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plain", "Bold", "Italics", "Bold & Italics" }));
        fontStyle.setBorder(null);
        fontStyle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fontStyleActionPerformed(evt);
            }
        });

        jLabel3.setText("Font Size");

        fontSize.setModel(new javax.swing.SpinnerNumberModel(14, 1, null, 1));
        fontSize.setBorder(null);

        okChangeFont.setText("OK");
        okChangeFont.setBorder(null);
        okChangeFont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okChangeFontActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.setBorder(null);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(okChangeFont, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(42, 42, 42)
                        .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(156, 156, 156))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(104, 104, 104))
                    .addComponent(fontType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fontStyle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(84, 84, 84))
                    .addComponent(fontSize))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fontType, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fontStyle, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addComponent(fontSize, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(okChangeFont, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fontTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fontTypeActionPerformed
        
    }//GEN-LAST:event_fontTypeActionPerformed

    private void fontStyleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fontStyleActionPerformed
        
    }//GEN-LAST:event_fontStyleActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okChangeFontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okChangeFontActionPerformed
        Font F ;
        
        if(fontStyle.getSelectedItem().toString().equals("Bold"))
        {
            recentType= 1;
        }
        else if(fontStyle.getSelectedItem().toString().equals("Plain")){
            recentType=0;
        }
        else if(fontStyle.getSelectedItem().toString().equals("Bold & Italics"))
        {
            recentType=3;
        }
        else if(fontStyle.getSelectedItem().toString().equals("Italics"))
        {
            recentType=2;
        }
        F = new Font(fontType.getSelectedItem().toString(),recentType,fontSize.getValue().hashCode());
        chngFont.codeArea.setFont(F) ;
        this.dispose();
    }//GEN-LAST:event_okChangeFontActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JSpinner fontSize;
    private javax.swing.JComboBox<String> fontStyle;
    private javax.swing.JComboBox<String> fontType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton okChangeFont;
    // End of variables declaration//GEN-END:variables
}
